version: '3.8'

services:
  frontend:
    build: ./frontend/index.html
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./backend/main.py
    ports:
      - "5000:5000"


  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tb_analyzer
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
